[package]
name = "effective-train"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rust_decimal = "1.25.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1"
